### PR TITLE
Use individual lodash modules instead of the monolithic one

### LINKED ISSUE #11: Make lodash dependency more granular
Hi,

The dependency on `lodash` increases the bundle size of consuming applications. Could we switch to the packages for the individual `lodash` functions to `lodash.intersection`, `lodash.difference` etc.?

The update process is fairly trivial, would be happy to do a PR for it.

Thanks.

### PR DESCRIPTION
**Pull request by richard-viney**
Fixes #11

### CODE REVIEW

**Comment by richard-viney** [comment]
If we could get an updated NPM release with this change in that'd be great.

**Comment by richard-viney** [comment]
The build failure here doesn't seem related to the change in this PR as the tests pass locally.

**Comment by richard-viney** [comment]
@thebillg Anything we can do to help get this PR merged?

**Comment by thebillg** [comment]
I'll get it merged and publish a new one today. Expect it in 24 hours

**Comment by viruschidai** [comment]
cool, will get it merged soon.

**Comment by richard-viney** [comment]
Great thanks.

**Pull request merged**
